CREATE DATABASE NONAME
USE NONAME
CREATE TABLE STUDENTS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50)
)
INSERT INTO STUDENTS
VALUES('TOM')
INSERT INTO STUDENTS
VALUES('JANE')
INSERT INTO STUDENTS
VALUES('ELIZABETH')


CREATE TABLE UCHENIKI(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50)
)
INSERT INTO UCHENIKI
VALUES('CHRIS')
INSERT INTO UCHENIKI
VALUES('TOM')
INSERT INTO UCHENIKI
VALUES('JENIFFER')

SELECT NAME FROM STUDENTS
UNION
SELECT UCHENIKI.NAME FROM UCHENIKI;

SELECT NAME FROM STUDENTS
UNION ALL
SELECT UCHENIKI.NAME FROM UCHENIKI;

SELECT NAME 
FROM STUDENTS 


EXCEPT

SELECT NAME 
FROM UCHENIKI
